Add database
EvgenyGitH/java-filmorate pull request #11
Opened 2023-08-22 20:14 UTC by EvgenyGitH

2023-08-23 20:43 UTC, z8q requested changes

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film film) throws ValidationException {
Выполняю:
POST http://localhost:8080/films
с body:
```JSON
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 1,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}
```
В первом элементе genres не указал id

Получаю ответ с ошибкой:
```JSON
{
	"timestamp": "2023-08-23T20:13:00.238+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}
```
При этом фильм сохраняется в базу

Допускается сохранение дубликатов, стоит сделать проверку на уникальность набора полей.
Например проверить, что в базе нет фильма с таким же именем, датой релиза и продолжительностью

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/UserDbStorage.java
> +    public User addUser(User user) throws ValidationException {
Допускается добавление дублей пользователей

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public void validateUser(User user) throws ValidationException {
в 33-й строке падаем с NullPointerException, если передать объект без поля name

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/LikeDbStorage.java
> +    public void addLike(Long filmId, Long userId) {
При повторном лайке от одного пользователя на один и тот же фильм возникает ошибка 500:
```JSON
{
	"timestamp": "2023-08-23T20:23:58.681+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films/1/like/1"
}
```
В исключении, которое падает, есть причина. В логах выводится корректно. 
Но в ответном объекте можно было бы тоже указать

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/LikeDbStorage.java
> +    public void addLike(Long filmId, Long userId) {
У user-ов при повторном добавлении в друзья такая же ошибка

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FriendsDbStorage.java
> +    public void addFriend(Long userId, Long friendId) {
В таблице есть статус дружбы, если оба пользователя добавили друг друга в друзья, можно было бы ставить confirmed = true

2023-08-23 20:43 UTC, z8q commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS mpa CASCADE;
тут есть команда для удаления, есть ли необходимость в deleteDb.sql?

Все drop команды можно вывести наверх

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.getUserById(userId);
Если вызовы методов используем только для проверки наличия в базе, то можно не создавать поля.
либо еще можно под это сделать отдельный метод, который ничего не возвращает, либо boolean

2023-08-23 20:43 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String login;
Можно было бы некоторые поля через аннотации провалидировать.
Над email можно еще `@NotBlank` поставить, в нем проверка на null и пустую строку. `@Email` не проверяет на null.
Над логином тоже `@NotBlank` можно поставить.
Позволит убрать часть логики-валидации в сервисе

2023-08-23 22:28 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film film) throws ValidationException {
добавил проверку корректности указания жанра и проверку на дубль

2023-08-23 22:42 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/UserDbStorage.java
> +    public User addUser(User user) throws ValidationException {
добавил проверку на дубль

2023-08-23 22:58 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public void validateUser(User user) throws ValidationException {
перепроверил, при null   значение поля name устанавливается user.setName(user.getLogin()); . вроде все корректно работает

2023-08-24 01:35 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/LikeDbStorage.java
> +    public void addLike(Long filmId, Long userId) {
исправил

2023-08-24 01:46 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FriendsDbStorage.java
> +    public void addFriend(Long userId, Long friendId) {
есть такой метод :  
public boolean confirm(Long userId, Long friendId) {
        String sqlQuery = "UPDATE friends SET confirmed = true ...

2023-08-24 01:47 UTC, EvgenyGitH commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS mpa CASCADE;
это для тестов. Для удаления перед каждым тестом

2023-08-24 01:51 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.getUserById(userId);
исправил

2023-08-24 01:54 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String login;
Исправил

2023-08-24 20:49 UTC, z8q approved these changes

2023-08-24 20:52 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      private String login;
С этих аннотаций должны приходить ConstraintViolationException в случае некорректного запроса. Можно этот вид исключений отлавливать

2023-08-27 22:46 UTC, merged