fix after reset
EvgenyGitH/java-filmorate pull request #8
Opened 2023-07-11 16:23 UTC by EvgenyGitH

2023-07-12 14:13 UTC, z8q requested changes

2023-07-12 14:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
Валидацию лучше вынести в отдельный метод.
isBlank проверяет на isEmpty
isEmpty лишний. Плюс тут упадем с NullPointerException если name придет null.  Поэтому нужна проверка на null. 
Тут еще есть аннотация `@Valid` можно сделать проверки через аннотации над полями в объекте NotBlank, NotNull и т.д.

2023-07-12 14:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@") || user.getEmail() == null) {
на null нужно делать проверку в первую очередь, иначе будет ошибка, если email null

2023-07-12 14:13 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
по всем полям стоит сделать проверки на null

2023-07-12 14:13 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTests.java
> +public class FilmControllerTests {
Протестировано хорошо

2023-07-12 21:43 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
Правильно ли я понял : если мы делаем Валидацию через @Valid и проверки по полям NotBlank, NotNull и т.д., то выносить Валидацию в отдельный метод не требуется (т.к. там будет одна или две проверки) ? 

isBlank проверяет на isEmpty - да,  изменил проверку на null

С аннотацией  @Valid  и NotBlank, NotNull и т.д. у меня возникают сложности в написании тестов (я так понимаю мы этот вид тестирования будем проходить позже) поэтому я пока убрал аннотацию @Valid

2023-07-12 21:47 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@") || user.getEmail() == null) {
исправил

2023-07-12 21:56 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
done

2023-07-13 20:49 UTC, z8q approved these changes

2023-07-13 20:49 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getBirthday().isAfter(LocalDate.now())) {
тут возможно user.getBirthday() проверятся на null будет

2023-07-13 20:49 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty() || film.getName().isBlank()) {
Правильно
Разобраться с аннотациями в дальнейшем будет полезно, можно применить.
Например сейчас email проверяется только на наличие знака `@`
Но могут быть такие варианты:
user@@yandex.ru
yandex@user@ru
@user.yandex.ru
и т.д.

Помимо аннотаций `@NotNull`,  `@NotBlank` еще есть `@Email` - вот она хорошо валидирует почту

2023-07-23 16:54 UTC, merged