выполнено в соответствии с ТЗ 10
EvgenyGitH/java-filmorate pull request #9
Opened 2023-07-27 21:04 UTC by EvgenyGitH

2023-07-28 22:10 UTC, z8q requested changes

2023-07-28 22:10 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getEmail() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Допускается сохранение почты в таком виде "email": "@@bob"

Если для валидации использовать аннотацию @Email над полем в User, то проверка будет корректной.
Только при использовании валидационных аннотаций, в методе контроллера рядом с аргументом User user нужно еще ставить аннотацию @Valid, чтобы проверка заработала

2023-07-28 22:10 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getEmail() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
.isBlank() проверяет случаи .contains(" ") тоже

2023-07-28 22:10 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmById(filmId);
в строках 94-95 повторные обращения к мапе filmStorage.getFilmById(filmId).
Для работы c hashMap допустимо, но в следующем дз будут обращения к базе, там нужно будет сводить к одному вызову, чтобы не грузить базу повторяющимися запросами

2023-07-29 18:02 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
done

2023-07-29 18:04 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private UserStorage userStorage;
done

2023-07-29 18:07 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.validateUser(user);
done

2023-07-29 18:14 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Удалил аннотацию из Контроллера. Аннотации по операциям указаны в конечных методах.

2023-07-29 18:20 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getDescription().length() > 200) {
done

2023-07-29 18:32 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getEmail() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
добавил 
исправил

2023-07-29 18:45 UTC, EvgenyGitH commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getFilmById(filmId);
done

2023-07-30 06:42 UTC, z8q approved these changes

2023-08-13 18:29 UTC, merged